/** IPC channel names shared by main, preload and renderer. */
export const IPC = {
  // renderer -> main (invoke)
  tabsCreate: 'tabs:create',
  tabsClose: 'tabs:close',
  tabsActivate: 'tabs:activate',
  tabsNavigate: 'tabs:navigate',
  tabsBack: 'tabs:back',
  tabsForward: 'tabs:forward',
  tabsReload: 'tabs:reload',
  tabsStop: 'tabs:stop',
  tabsList: 'tabs:list',
  tabsMove: 'tabs:move',
  tabsMenu: 'tabs:menu',
  tabsDetach: 'tabs:detach',
  tabsAdopt: 'tabs:adopt',
  tabsMute: 'tabs:mute',
  openApp: 'ksuite:open-app',
  setContentBounds: 'layout:content-bounds',
  showAppMenu: 'ui:app-menu',
  showShieldMenu: 'ui:shield-menu',
  openSettingsPage: 'ui:open-settings',
  windowInfo: 'ui:window-info',
  suggest: 'ui:suggest',
  suggestShow: 'ui:suggest-show',
  suggestHide: 'ui:suggest-hide',
  suggestChoose: 'ui:suggest-choose',
  findStart: 'ui:find-start',
  findStop: 'ui:find-stop',
  zoomReset: 'ui:zoom-reset',
  bookmarkToggle: 'ui:bookmark-toggle',
  bookmarksList: 'ui:bookmarks-list',
  bookmarkOpen: 'ui:bookmark-open',
  bookmarkMenu: 'ui:bookmark-menu',
  bookmarksMenu: 'ui:bookmarks-menu',
  updateInstall: 'ui:update-install',
  updateStatus: 'ui:update-status',
  passwordAnswer: 'ui:password-answer',
  passwordUnlock: 'ui:password-unlock',

  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  tokenStatus: 'token:status',

  apiProfile: 'api:profile',
  apiDriveList: 'api:drive-list',
  apiDriveSearch: 'api:drive-search',
  apiDriveDownload: 'api:drive-download',
  apiDriveUpload: 'api:drive-upload',
  apiDriveOpenWeb: 'api:drive-open-web',
  apiSavePageToDrive: 'api:save-page-to-drive',
  apiMailOverview: 'api:mail-overview',
  apiMailSend: 'api:mail-send',
  apiCalendarUpcoming: 'api:calendar-upcoming',
  apiCalendarCreate: 'api:calendar-create',

  downloadsList: 'downloads:list',
  downloadsOpen: 'downloads:open',

  // main -> renderer (events)
  evTabs: 'ev:tabs',
  evDownloads: 'ev:downloads',
  evFocusAddress: 'ev:focus-address',
  evTogglePanel: 'ev:toggle-panel',
  evComposeMail: 'ev:compose-mail',
  evToast: 'ev:toast',
  evSettings: 'ev:settings',
  evBookmarks: 'ev:bookmarks',
  evFind: 'ev:find',
  evFindNext: 'ev:find-next',
  evFindResult: 'ev:find-result',
  evPasswordPrompt: 'ev:password-prompt',
  evPasswordUnlock: 'ev:password-unlock',
  evUnread: 'ev:unread',
  evUpdate: 'ev:update',
} as const;

/** Channels of the internal pages (ksuite://…), see src/preload/page.ts. */
export const INTERNAL = {
  settingsGet: 'internal:settings:get',
  settingsSet: 'internal:settings:set',
  tokenStatus: 'internal:token:status',
  tokenSet: 'internal:token:set',
  tokenClear: 'internal:token:clear',
  drives: 'internal:drives',
  clearData: 'internal:data:clear',
  chooseDownloadDir: 'internal:downloads:choose-dir',
  downloadDirInfo: 'internal:downloads:dir',
  about: 'internal:about',
  httpsContinue: 'internal:https-only:continue',
  historySearch: 'internal:history:search',
  historyRemove: 'internal:history:remove',
  historyClear: 'internal:history:clear',
  bookmarksList: 'internal:bookmarks:list',
  bookmarksUpdate: 'internal:bookmarks:update',
  bookmarksRemove: 'internal:bookmarks:remove',
  bookmarksShift: 'internal:bookmarks:shift',
  bookmarksImport: 'internal:bookmarks:import',
  bookmarksAdd: 'internal:bookmarks:add',
  pwStatus: 'internal:pw:status',
  pwUnlock: 'internal:pw:unlock',
  pwLock: 'internal:pw:lock',
  pwList: 'internal:pw:list',
  pwNever: 'internal:pw:never',
  pwAdd: 'internal:pw:add',
  pwUpdate: 'internal:pw:update',
  pwRemove: 'internal:pw:remove',
  pwRemoveNever: 'internal:pw:remove-never',
  pwSetPrimary: 'internal:pw:set-primary',
  pwRemovePrimary: 'internal:pw:remove-primary',
  pwImport: 'internal:pw:import',
  pwExport: 'internal:pw:export',
  pwGenerate: 'internal:pw:generate',
  testNotification: 'internal:notifications:test',
  updateStatus: 'internal:update:status',
  updateCheck: 'internal:update:check',
  updateDownload: 'internal:update:download',
  updateInstall: 'internal:update:install',
  updateOpenRelease: 'internal:update:open-release',
  newtabData: 'internal:newtab:data',
  newtabHide: 'internal:newtab:hide',
  newtabRestore: 'internal:newtab:restore',
  newtabFocusOmnibox: 'internal:newtab:focus-omnibox',
  evSettings: 'internal:ev:settings',
  evBookmarks: 'internal:ev:bookmarks',
  evUpdate: 'internal:ev:update',
} as const;
